/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noindex?: boolean;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            reference?: PageReference | PostReference;
            _type: "internalLink";
            _key: string;
          }
        | {
            href?: string;
            blank?: boolean;
            _type: "externalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | {
      type?: "tip" | "warning" | "info";
      title?: string;
      text: string;
      _type: "calloutBox";
      _key: string;
    }
  | {
      name: string;
      description: string;
      reps?: string;
      _type: "exerciseCard";
      _key: string;
    }
  | {
      url: string;
      _type: "youtube";
      _key: string;
    }
>;

export type DeploymentRequest = {
  _id: string;
  _type: "deploymentRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  requestedAt: string;
  requestId: string;
  requestedById: string;
  requestedByName?: string;
  note?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  seo?: Seo;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  content?: BlockContent;
  faq?: Array<{
    question: string;
    answer: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  excerpt: string;
  body?: BlockContent;
  faq?: Array<{
    question: string;
    answer: string;
    _key: string;
  }>;
  takeaways?: Array<string>;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: BlockContent;
};

export type MediaFolderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "media.folder";
};

export type MediaFolder = {
  _id: string;
  _type: "media.folder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | PageReference
  | PostReference
  | BlockContent
  | DeploymentRequest
  | SiteSettings
  | Category
  | Slug
  | Page
  | AuthorReference
  | CategoryReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/utils/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    "title": coalesce(title, siteTitle, defaultSeoTitle, "ZádaBezBolesti.cz"),    "description": coalesce(description, defaultSeoDescription, "Praktický průvodce ergonomií a zdravým pohybem"),    seo  }
export type SiteSettingsQueryResult = {
  title: string;
  description: string;
  seo: Seo | null;
} | null;

// Source: src/utils/queries.ts
// Variable: allPagesQuery
// Query: *[_type == "page" && defined(slug.current)] | order(slug.current asc) {    title,    "slug": slug.current,    _updatedAt  }
export type AllPagesQueryResult = Array<{
  title: string;
  slug: string;
  _updatedAt: string;
}>;

// Source: src/utils/queries.ts
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    _type,    title,    "slug": slug.current,    content[] {        ...,  _type == "block" => {    ...,    markDefs[] {      ...,      _type == "internalLink" => {        "reference": reference->{          _type,          title,          "slug": slug.current        }      }    }  }    },    sections[] {      _key,      _type,      heading,      title,      variant,      text[] {          ...,  _type == "block" => {    ...,    markDefs[] {      ...,      _type == "internalLink" => {        "reference": reference->{          _type,          title,          "slug": slug.current        }      }    }  }      },      content[] {          ...,  _type == "block" => {    ...,    markDefs[] {      ...,      _type == "internalLink" => {        "reference": reference->{          _type,          title,          "slug": slug.current        }      }    }  }      },      items[] {        title,        description      }    },    faq[] {      question,      answer    },    seo  }
export type PageQueryResult = {
  _id: string;
  _type: "page";
  title: string;
  slug: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              href?: string;
              blank?: boolean;
              _type: "externalLink";
              _key: string;
            }
          | {
              reference:
                | {
                    _type: "page";
                    title: string;
                    slug: string;
                  }
                | {
                    _type: "post";
                    title: string;
                    slug: string;
                  }
                | null;
              _type: "internalLink";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        type?: "info" | "tip" | "warning";
        title?: string;
        text: string;
        _type: "calloutBox";
        _key: string;
      }
    | {
        name: string;
        description: string;
        reps?: string;
        _type: "exerciseCard";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        url: string;
        _type: "youtube";
        _key: string;
      }
  > | null;
  sections: null;
  faq: Array<{
    question: string;
    answer: string;
  }> | null;
  seo: Seo | null;
} | null;

// Source: src/utils/queries.ts
// Variable: allPostsQuery
// Query: *[_type in ["post", "article"] && defined(slug.current)] | order(coalesce(publishedAt, publishDate, _createdAt) desc) {    _id,    title,    "slug": slug.current,    "publishedAt": coalesce(publishedAt, publishDate, _createdAt),    "excerpt": coalesce(excerpt, lead, ""),    mainImage,    author->{      name,      "slug": slug.current,      image    },    categories[]->{      title,      "slug": slug.current    }  }
export type AllPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  publishedAt: string;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  author: {
    name: string;
    slug: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  categories: Array<{
    title: string;
    slug: string;
  }> | null;
}>;

// Source: src/utils/queries.ts
// Variable: postQuery
// Query: *[_type in ["post", "article"] && slug.current == $slug][0] {    _id,    _type,    title,    "slug": slug.current,    "publishedAt": coalesce(publishedAt, publishDate, _createdAt),    "excerpt": coalesce(excerpt, lead, ""),    mainImage,    author->{      name,      "slug": slug.current,      image,      bio    },    categories[]->{      title,      "slug": slug.current    },    "body": coalesce(body, content, []),    sections[] {      _key,      _type,      heading,      title,      variant,      text[] {          ...,  _type == "block" => {    ...,    markDefs[] {      ...,      _type == "internalLink" => {        "reference": reference->{          _type,          title,          "slug": slug.current        }      }    }  }      },      content[] {          ...,  _type == "block" => {    ...,    markDefs[] {      ...,      _type == "internalLink" => {        "reference": reference->{          _type,          title,          "slug": slug.current        }      }    }  }      },      items[] {        title,        description      }    },    faq[] {      question,      answer    },    takeaways,    seo  }
export type PostQueryResult = {
  _id: string;
  _type: "post";
  title: string;
  slug: string;
  publishedAt: string;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  author: {
    name: string;
    slug: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    bio: BlockContent | null;
  } | null;
  categories: Array<{
    title: string;
    slug: string;
  }> | null;
  body: Array<never> | BlockContent;
  sections: null;
  faq: Array<{
    question: string;
    answer: string;
  }> | null;
  takeaways: Array<string> | null;
  seo: Seo | null;
} | null;

// Source: src/utils/queries.ts
// Variable: allCategoriesQuery
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    title,    "slug": slug.current,    description  }
export type AllCategoriesQueryResult = Array<{
  title: string;
  slug: string;
  description: string | null;
}>;

// Source: src/utils/queries.ts
// Variable: categoryQuery
// Query: *[_type == "category" && slug.current == $slug][0] {    title,    "slug": slug.current,    description  }
export type CategoryQueryResult = {
  title: string;
  slug: string;
  description: string | null;
} | null;

// Source: src/utils/queries.ts
// Variable: postsByCategoryQuery
// Query: *[_type in ["post", "article"] && defined(slug.current) && $categorySlug in categories[]->slug.current] | order(coalesce(publishedAt, publishDate, _createdAt) desc) {    _id,    title,    "slug": slug.current,    "publishedAt": coalesce(publishedAt, publishDate, _createdAt),    "excerpt": coalesce(excerpt, lead, ""),    mainImage,    author->{      name,      "slug": slug.current,      image    },    categories[]->{      title,      "slug": slug.current    }  }
export type PostsByCategoryQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  publishedAt: string;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  author: {
    name: string;
    slug: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  categories: Array<{
    title: string;
    slug: string;
  }> | null;
}>;

// Source: studio/tools/deploy/queries.ts
// Variable: deployToolStateQuery
// Query: {  "lastRequest": *[_id == "deploymentRequest" && _type == "deploymentRequest"][0] {    requestId, requestedAt, requestedById, requestedByName, note  },  "draftCount": count(*[_id in path("drafts.**") && _type in $trackedTypes])}
export type DeployToolStateQueryResult = {
  lastRequest: {
    requestId: string;
    requestedAt: string;
    requestedById: string;
    requestedByName: string | null;
    note: string | null;
  } | null;
  draftCount: number;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0] {\n    "title": coalesce(title, siteTitle, defaultSeoTitle, "Z\xE1daBezBolesti.cz"),\n    "description": coalesce(description, defaultSeoDescription, "Praktick\xFD pr\u016Fvodce ergonomi\xED a zdrav\xFDm pohybem"),\n    seo\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "page" && defined(slug.current)] | order(slug.current asc) {\n    title,\n    "slug": slug.current,\n    _updatedAt\n  }\n': AllPagesQueryResult;
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    content[] {\n      \n  ...,\n  _type == "block" => {\n    ...,\n    markDefs[] {\n      ...,\n      _type == "internalLink" => {\n        "reference": reference->{\n          _type,\n          title,\n          "slug": slug.current\n        }\n      }\n    }\n  }\n\n    },\n    sections[] {\n      _key,\n      _type,\n      heading,\n      title,\n      variant,\n      text[] {\n        \n  ...,\n  _type == "block" => {\n    ...,\n    markDefs[] {\n      ...,\n      _type == "internalLink" => {\n        "reference": reference->{\n          _type,\n          title,\n          "slug": slug.current\n        }\n      }\n    }\n  }\n\n      },\n      content[] {\n        \n  ...,\n  _type == "block" => {\n    ...,\n    markDefs[] {\n      ...,\n      _type == "internalLink" => {\n        "reference": reference->{\n          _type,\n          title,\n          "slug": slug.current\n        }\n      }\n    }\n  }\n\n      },\n      items[] {\n        title,\n        description\n      }\n    },\n    faq[] {\n      question,\n      answer\n    },\n    seo\n  }\n': PageQueryResult;
    '\n  *[_type in ["post", "article"] && defined(slug.current)] | order(coalesce(publishedAt, publishDate, _createdAt) desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    "publishedAt": coalesce(publishedAt, publishDate, _createdAt),\n    "excerpt": coalesce(excerpt, lead, ""),\n    mainImage,\n    author->{\n      name,\n      "slug": slug.current,\n      image\n    },\n    categories[]->{\n      title,\n      "slug": slug.current\n    }\n  }\n': AllPostsQueryResult;
    '\n  *[_type in ["post", "article"] && slug.current == $slug][0] {\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    "publishedAt": coalesce(publishedAt, publishDate, _createdAt),\n    "excerpt": coalesce(excerpt, lead, ""),\n    mainImage,\n    author->{\n      name,\n      "slug": slug.current,\n      image,\n      bio\n    },\n    categories[]->{\n      title,\n      "slug": slug.current\n    },\n    "body": coalesce(body, content, []),\n    sections[] {\n      _key,\n      _type,\n      heading,\n      title,\n      variant,\n      text[] {\n        \n  ...,\n  _type == "block" => {\n    ...,\n    markDefs[] {\n      ...,\n      _type == "internalLink" => {\n        "reference": reference->{\n          _type,\n          title,\n          "slug": slug.current\n        }\n      }\n    }\n  }\n\n      },\n      content[] {\n        \n  ...,\n  _type == "block" => {\n    ...,\n    markDefs[] {\n      ...,\n      _type == "internalLink" => {\n        "reference": reference->{\n          _type,\n          title,\n          "slug": slug.current\n        }\n      }\n    }\n  }\n\n      },\n      items[] {\n        title,\n        description\n      }\n    },\n    faq[] {\n      question,\n      answer\n    },\n    takeaways,\n    seo\n  }\n': PostQueryResult;
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) {\n    title,\n    "slug": slug.current,\n    description\n  }\n': AllCategoriesQueryResult;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    title,\n    "slug": slug.current,\n    description\n  }\n': CategoryQueryResult;
    '\n  *[_type in ["post", "article"] && defined(slug.current) && $categorySlug in categories[]->slug.current] | order(coalesce(publishedAt, publishDate, _createdAt) desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    "publishedAt": coalesce(publishedAt, publishDate, _createdAt),\n    "excerpt": coalesce(excerpt, lead, ""),\n    mainImage,\n    author->{\n      name,\n      "slug": slug.current,\n      image\n    },\n    categories[]->{\n      title,\n      "slug": slug.current\n    }\n  }\n': PostsByCategoryQueryResult;
    '{\n  "lastRequest": *[_id == "deploymentRequest" && _type == "deploymentRequest"][0] {\n    requestId, requestedAt, requestedById, requestedByName, note\n  },\n  "draftCount": count(*[_id in path("drafts.**") && _type in $trackedTypes])\n}': DeployToolStateQueryResult;
  }
}
